### ISSUE TITLE
surge 2024.3.1开始自动重启

### ISSUE THREAD

**Issue by liuzhe101** [QiuChenlyOpenSource/91QiuChen#22]
surge版本 ：5.4.4 （2577）
Macos :14.3.1
操作步骤：跟往常一样操作，退出surge（从家中到公司不退出，wifi网络环境切换，无法自动连接网络，本地无网络，退出再打开surge网络正常），打开surge，开启代理和增强。然后自动隔几分钟重启
重启次数：7
<img width="764" alt="image" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/61652514/79525ff4-6350-4a3d-bc55-726fb04199a5">
[Surge-2024-03-01-091103.log](https://github.com/QiuChenlyOpenSource/91QiuChen/files/14455353/Surge-2024-03-01-091103.log)

**Comment by Eirperuier** [comment]
同样有这个问题
surge版本: 5.5.0 (2586)
似乎是主界面反复崩溃自动重启
![CleanShot 2024-03-01 at 15 52 34@2x](https://github.com/QiuChenlyOpenSource/91QiuChen/assets/60021832/c79923c0-fd3d-4897-8193-81cd6a1d4aec)

**Comment by BailinSong** [comment]
一样的问题 测试了几个版本 都是有这个问题

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Surge [779]
Path:                  /Applications/Surge.app/Contents/MacOS/Surge
Identifier:            com.nssurge.surge-mac
Version:               5.4.4 (2583)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-03-01 16:17:17.5046 +0800
OS Version:            macOS 14.3.1 (23D60)
Report Version:        12
Bridge OS Version:     8.3 (21P3049)
Anonymous UUID:        42E9022C-B5BE-ABDA-8EB4-E10AA62E205A


Time Awake Since Boot: 590 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGILL)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   Surge [779]

Application Specific Information:
BUG IN CLIENT OF LIBDISPATCH: Release of a suspended object
Abort Cause 297235947613847552


Kernel Triage:
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	    0x7ff805892e83 AutoreleasePoolPage::add(objc_object*) + 211
1   libobjc.A.dylib               	    0x7ff80587248a objc_object::rootAutorelease2() + 66
2   Foundation                    	    0x7ff806c5f39b readARCWeakAt + 20
3   Foundation                    	    0x7ff806c57651 -[NSConcreteMapTable objectForKey:] + 95
4   AppKit                        	    0x7ff80934a0d6 +[NSCGSWindow(NSCGSWindowCreation) windowWithWindowID:] + 69
5   AppKit                        	    0x7ff8095de921 _NSSetWindowAlpha + 36
6   AppKit                        	    0x7ff80936f20c NSPerformVisuallyAtomicChange + 134
7   AppKit                        	    0x7ff809537b3c -[NSWindow setAlphaValue:] + 126
8   AppKit                        	    0x7ff809b162a7 -[NSPopupMenuWindow setAlphaValue:] + 58
9   Foundation                    	    0x7ff806c779b3 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 705
10  Foundation                    	    0x7ff806ca1aae -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 68
11  Foundation                    	    0x7ff806cf29fb _NSSetDoubleValueAndNotify + 280
12  Foundation                    	    0x7ff806c82719 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 316
13  AppKit                        	    0x7ff809577f35 -[NSWindow setValue:forKey:] + 111
14  QuartzCore                    	    0x7ff80e240a07 -[CABasicAnimation applyForTime:presentationObject:modelObject:] + 843
15  AppKit                        	    0x7ff809312506 +[NSAppearance _performWithCurrentAppearance:usingBlock:] + 68
16  AppKit                        	    0x7ff8094d8693 __40+[NSAnimationManager performAnimations:]_block_invoke_3 + 840
17  AppKit                        	    0x7ff80933ea48 +[NSAnimationContext runAnimationGroup:] + 56
18  AppKit                        	    0x7ff8094d8342 __40+[NSAnimationManager performAnimations:]_block_invoke_2 + 138
19  AppKit                        	    0x7ff80936f20c NSPerformVisuallyAtomicChange + 134
20  AppKit                        	    0x7ff8094d7ec4 +[NSAnimationManager performAnimations:] + 1225
21  AppKit                        	    0x7ff8094d7951 -[NSScreenDisplayLink _fire] + 156
22  AppKit                        	    0x7ff80a038c91 ___NSRunLoopTimerCreateWithHandler_block_invoke + 34
23  CoreFoundation                	    0x7ff805d313ac __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
24  CoreFoundation                	    0x7ff805d30f5a __CFRunLoopDoTimer + 785
25  CoreFoundation                	    0x7ff805d30b96 __CFRunLoopDoTimers + 285
26  CoreFoundation                	    0x7ff805d14e82 __CFRunLoopRun + 2104
27  CoreFoundation                	    0x7ff805d14082 CFRunLoopRunSpecific + 557
28  HIToolbox                     	    0x7ff8106069d9 RunCurrentEventLoopInMode + 292
29  HIToolbox                     	    0x7ff8106067e6 ReceiveNextEventCommon + 665
30  HIToolbox                     	    0x7ff810606531 _BlockUntilNextEventMatchingListInModeWithFilter + 66
31  AppKit                        	    0x7ff809324c39 _DPSNextEvent + 880
32  AppKit                        	    0x7ff809c2e804 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1304
33  AppKit                        	    0x7ff809a306fd -[NSMenuTrackingSession startRunningMenuEventLoop:] + 334
34  AppKit                        	    0x7ff80a252a5c -[NSContextMenuTrackingSession startMonitoringEventsInMode:] + 88
35  AppKit                        	    0x7ff8099df857 +[NSContextMenuImpl presentPopup:fromView:withContext:animated:] + 835
36  AppKit                        	    0x7ff809c5f31d _NSPopUpMenu + 3156
37  AppKit                        	    0x7ff809c5e62f -[NSCocoaMenuImpl popUpMenu:atLocation:width:view:selectedItemIndexProvider:font:positioningRect:flags:options:] + 580
38  AppKit                        	    0x7ff809c5e3e5 -[NSCocoaMenuImpl popUpMenu:atLocation:width:view:selectedItemIndexProvider:font:flags:options:] + 53
39  AppKit                        	    0x7ff809c5e3a0 -[NSCocoaMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 81
40  AppKit                        	    0x7ff809c1f6ce +[NSStatusBarButtonCell popUpStatusBarMenu:ofItem:ofBar:inRect:ofView:withEvent:] + 417
41  AppKit                        	    0x7ff809c22967 -[NSStatusItem popUpStatusItemMenu:] + 141
42  Surge                         	       0x10f767e87 0x10f59c000 + 1883783
43  Foundation                    	    0x7ff806cd0179 __NSFireDelayedPerform + 438
44  CoreFoundation                	    0x7ff805d313ac __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
45  CoreFoundation                	    0x7ff805d30f5a __CFRunLoopDoTimer + 785
46  CoreFoundation                	    0x7ff805d30b96 __CFRunLoopDoTimers + 285
47  CoreFoundation                	    0x7ff805d14e82 __CFRunLoopRun + 2104
48  CoreFoundation                	    0x7ff805d14082 CFRunLoopRunSpecific + 557
49  HIToolbox                     	    0x7ff8106069d9 RunCurrentEventLoopInMode + 292
50  HIToolbox                     	    0x7ff8106067e6 ReceiveNextEventCommon + 665
51  HIToolbox                     	    0x7ff810606531 _BlockUntilNextEventMatchingListInModeWithFilter + 66
52  AppKit                        	    0x7ff809324c39 _DPSNextEvent + 880
53  AppKit                        	    0x7ff809c2e804 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1304
54  AppKit                        	    0x7ff8093161b2 -[NSApplication run] + 603
55  AppKit                        	    0x7ff8092ea1c1 NSApplicationMain + 816
56  Surge                         	       0x10f8667e3 0x10f59c000 + 2926563
57  dyld                          	    0x7ff8058af386 start + 1942

Thread 1:: KSCrash Exception Handler (Secondary)
0   libsystem_kernel.dylib        	    0x7ff805bfaa2e mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff805c08e3a mach_msg2_internal + 84
2   libsystem_kernel.dylib        	    0x7ff805c01b62 mach_msg_overwrite + 653
3   libsystem_kernel.dylib        	    0x7ff805bfad1f mach_msg + 19
4   Bugsnag                       	       0x1104e1f96 ksmachexc_i_handleExceptions + 165
5   libsystem_pthread.dylib       	    0x7ff805c3a202 _pthread_start + 99
6   libsystem_pthread.dylib       	    0x7ff805c35bab thread_start + 15

Thread 2:: com.bugsnag.app-hang-detector
0   libsystem_kernel.dylib        	    0x7ff805bfa9c2 semaphore_timedwait_trap + 10
1   libdispatch.dylib             	    0x7ff805a92aeb _dispatch_sema4_timedwait + 73
2   libdispatch.dylib             	    0x7ff805a92f37 _dispatch_semaphore_wait_slow + 58
3   Bugsnag                       	       0x1104e6b82 -[BSGAppHangDetector detectAppHangs] + 182
4   Bugsnag                       	       0x1104e6ac8 DetectAppHangs + 9
5   libsystem_pthread.dylib       	    0x7ff805c3a202 _pthread_start + 99
6   libsystem_pthread.dylib       	    0x7ff805c35bab thread_start + 15

Thread 3:: com.apple.NSEventThread
0   libsystem_c.dylib             	    0x7ff805adc001 __vfprintf + 4007
1   libsystem_c.dylib             	    0x7ff805b08ff8 _vsnprintf + 257
2   libsystem_c.dylib             	    0x7ff805ae6f63 vsnprintf_l + 41
3   libsystem_c.dylib             	    0x7ff805ae7019 snprintf + 156
4   SkyLight                      	    0x7ff80b3e6931 (anonymous namespace)::EventLog::getLogString() const + 277
5   SkyLight                      	    0x7ff80b3e7e0a (anonymous namespace)::SystemDefinedEventLog::getLogString() const + 76
6   SkyLight                      	    0x7ff80b3e602d CGSEventLogEvent + 361
7   SkyLight                      	    0x7ff80b60fd61 SLSGetNextEventRecordInternal + 332
8   SkyLight                      	    0x7ff80b3d66db SLEventCreateNextEvent + 9
9   HIToolbox                     	    0x7ff810611922 PullEventsFromWindowServerOnConnection(unsigned int, unsigned char, __CFMachPortBoost*) + 45
10  HIToolbox                     	    0x7ff8106118c2 MessageHandler(__CFMachPort*, void*, long, void*) + 48
11  CoreFoundation                	    0x7ff805d4487c __CFMachPortPerform + 238
12  CoreFoundation                	    0x7ff805d16527 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
13  CoreFoundation                	    0x7ff805d1645e __CFRunLoopDoSource1 + 534
14  CoreFoundation                	    0x7ff805d150d6 __CFRunLoopRun + 2700
15  CoreFoundation                	    0x7ff805d14082 CFRunLoopRunSpecific + 557
16  AppKit                        	    0x7ff809481aac _NSEventThread + 122
17  libsystem_pthread.dylib       	    0x7ff805c3a202 _pthread_start + 99
18  libsystem_pthread.dylib       	    0x7ff805c35bab thread_start + 15

Thread 4:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	    0x7ff805bfaa2e mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff805c08e3a mach_msg2_internal + 84
2   libsystem_kernel.dylib        	    0x7ff805c01b62 mach_msg_overwrite + 653
3   libsystem_kernel.dylib        	    0x7ff805bfad1f mach_msg + 19
4   CoreFoundation                	    0x7ff805d16135 __CFRunLoopServiceMachPort + 143
5   CoreFoundation                	    0x7ff805d14ba5 __CFRunLoopRun + 1371
6   CoreFoundation                	    0x7ff805d14082 CFRunLoopRunSpecific + 557
7   CFNetwork                     	    0x7ff80b074dd5 0x7ff80ae2d000 + 2391509
8   Foundation                    	    0x7ff806ca871c __NSThread__start__ + 1013
9   libsystem_pthread.dylib       	    0x7ff805c3a202 _pthread_start + 99
10  libsystem_pthread.dylib       	    0x7ff805c35bab thread_start + 15

Thread 5:
0   libsystem_pthread.dylib       	    0x7ff805c35b88 start_wqthread + 0

Thread 6::  Dispatch queue: SGSocket-1107
0   libdispatch.dylib             	    0x7ff805ac2812 _dispatch_queue_xref_dispose.cold.1 + 24
1   libdispatch.dylib             	    0x7ff805a97869 _dispatch_queue_xref_dispose + 50
2   libdispatch.dylib             	    0x7ff805a92059 -[OS_dispatch_source _xref_dispose] + 17
3   Surge                         	       0x10f5a8f9d 0x10f59c000 + 53149
4   Surge                         	       0x10f717cf5 0x10f59c000 + 1555701
5   libdispatch.dylib             	    0x7ff805a912e6 _dispatch_call_block_and_release + 12
6   libdispatch.dylib             	    0x7ff805a9259a _dispatch_client_callout + 8
7   libdispatch.dylib             	    0x7ff805a98668 _dispatch_lane_serial_drain + 816
8   libdispatch.dylib             	    0x7ff805a99100 _dispatch_lane_invoke + 377
9   libdispatch.dylib             	    0x7ff805aa2aee _dispatch_root_queue_drain_deferred_wlh + 271
10  libdispatch.dylib             	    0x7ff805aa23fd _dispatch_workloop_worker_thread + 451
11  libsystem_pthread.dylib       	    0x7ff805c36c47 _pthread_wqthread + 327
12  libsystem_pthread.dylib       	    0x7ff805c35b97 start_wqthread + 15

Thread 7::  Dispatch queue: SGJournalRecordContainerMacOS
0   libobjc.A.dylib               	    0x7ff805893a3c AutoreleasePoolPage::push() + 146
1   CoreFoundation                	    0x7ff805ca3c43 _CFAutoreleasePoolPush + 11
2   CoreFoundation                	    0x7ff805d17a93 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 219
3   Surge                         	       0x10f5f9121 0x10f59c000 + 381217
4   Surge                         	       0x10f71804a 0x10f59c000 + 1556554
5   libdispatch.dylib             	    0x7ff805a9259a _dispatch_client_callout + 8
6   libdispatch.dylib             	    0x7ff805a950c7 _dispatch_continuation_pop + 523
7   libdispatch.dylib             	    0x7ff805aa56f8 _dispatch_source_invoke + 2076
8   libdispatch.dylib             	    0x7ff805a984bb _dispatch_lane_serial_drain + 387
9   libdispatch.dylib             	    0x7ff805a99100 _dispatch_lane_invoke + 377
10  libdispatch.dylib             	    0x7ff805aa2aee _dispatch_root_queue_drain_deferred_wlh + 271
11  libdispatch.dylib             	    0x7ff805aa23fd _dispatch_workloop_worker_thread + 451
12  libsystem_pthread.dylib       	    0x7ff805c36c47 _pthread_wqthread + 327
13  libsystem_pthread.dylib       	    0x7ff805c35b97 start_wqthread + 15

Thread 8:
0   libsystem_pthread.dylib       	    0x7ff805c35b88 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	    0x7ff805c35b88 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	    0x7ff805c35b88 start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib       	    0x7ff805c35b88 start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib       	    0x7ff805c35b88 start_wqthread + 0


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007f77d41f7640  rbx: 0x00007f77d618bd30  rcx: 0x00007f77d41f7638  rdx: 0x0000000000000000
  rdi: 0x00007f77d41f7000  rsi: 0x00007f77d41f7038  rbp: 0x00007ff7b095edc0  rsp: 0x00007ff7b095ed90
   r8: 0x0000000000001a00   r9: 0x0000000000000001  r10: 0x00007ff84927a110  r11: 0x00007ff806c575f2
  r12: 0x0000ffffffffffff  r13: 0x0000600003aa0c80  r14: 0x00007f77d41f7638  r15: 0xfffeffffffffffff
  rip: 0x00007ff805892e83  rfl: 0x0000000000000206  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000 
Trap Number:     222


Binary Images:
       0x110386000 -        0x110395fff libobjc-trampolines.dylib (*) <06997eb3-387c-3024-b943-376aa535a09c> /usr/lib/libobjc-trampolines.dylib
       0x11026a000 -        0x110281fff com.diephouse.matt.MMMarkdown (1.0) <d6d173dc-bfa7-3541-9191-5ad69dd76afd> /Applications/Surge.app/Contents/Frameworks/MMMarkdown.framework/Versions/A/MMMarkdown
       0x1104b3000 -        0x1104fafff com.bugsnag.Bugsnag (6.27.0) <00f849b0-d25a-3fab-95f4-f795f9342e8d> /Applications/Surge.app/Contents/Frameworks/Bugsnag.framework/Versions/A/Bugsnag
       0x11056b000 -        0x1105aefff org.sparkle-project.Sparkle (1.23.0) <8c5e572d-cdce-3d55-bfb3-75fdea2ba783> /Applications/Surge.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x110607000 -        0x11066efff libInjectLib.dylib (*) <0149efd8-c47b-3f8c-93b3-7dd1c99a4cdf> /Applications/Surge.app/Contents/Frameworks/libInjectLib.dylib
       0x10f59c000 -        0x10fc93fff com.nssurge.surge-mac (5.4.4) <37dea691-2c85-385a-a4b9-c2661b36753f> /Applications/Surge.app/Contents/MacOS/Surge
    0x7ff805867000 -     0x7ff8058a8ff8 libobjc.A.dylib (*) <ea826a22-4354-3747-ab9f-371e1ab11bed> /usr/lib/libobjc.A.dylib
    0x7ff806c53000 -     0x7ff80788aff3 com.apple.Foundation (6.9) <6589cc92-b39e-392c-808b-b20538f9312f> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7ff8092e6000 -     0x7ff80a704ff6 com.apple.AppKit (6.9) <660b78d6-113f-3abd-8969-a6cb84fff752> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7ff80e1ff000 -     0x7ff80e5a6ff9 com.apple.QuartzCore (1.11) <a3ee0b69-3efd-3505-bf79-1068ea77fe90> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7ff805c9a000 -     0x7ff806134fec com.apple.CoreFoundation (6.9) <d9705b29-47af-343b-ba26-5cda3166731e> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff8105d6000 -     0x7ff810871ff4 com.apple.HIToolbox (2.1.1) <4cd47f03-ed80-3f2a-bbdf-d7af11cb4ccb> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7ff8058a9000 -     0x7ff8059453ff dyld (*) <01ae3ae3-f6ca-34d1-a2f8-462ede5fa818> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff805bf9000 -     0x7ff805c33ff7 libsystem_kernel.dylib (*) <3e22fb41-20e3-3568-a00b-d8e901e333bf> /usr/lib/system/libsystem_kernel.dylib
    0x7ff805c34000 -     0x7ff805c3ffff libsystem_pthread.dylib (*) <0f6c8ecc-a9bd-39c6-9f41-a8b9159201eb> /usr/lib/system/libsystem_pthread.dylib
    0x7ff805a8f000 -     0x7ff805ad5ffd libdispatch.dylib (*) <c964889c-7792-333d-93f6-8f3e51a9f4c2> /usr/lib/system/libdispatch.dylib
    0x7ff805ad9000 -     0x7ff805b60fff libsystem_c.dylib (*) <6f840a77-9f88-3da8-83ac-98e4892282d0> /usr/lib/system/libsystem_c.dylib
    0x7ff80b29b000 -     0x7ff80b6f3ff1 com.apple.SkyLight (1.600.0) <44c36221-6308-3df3-821f-755130080968> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7ff80ae2d000 -     0x7ff80b1dbff1 com.apple.CFNetwork (1.0) <2847065d-8c66-3a44-b26c-b2a51a2897fb> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=722.4M resident=0K(0%) swapped_out_or_unallocated=722.4M(100%)
Writable regions: Total=661.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=661.6M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
Activity Tracing                   256K        1 
CG image                           916K       51 
ColorSync                          236K       30 
CoreAnimation                     3412K      278 
CoreGraphics                        16K        3 
CoreUI image data                 2044K       27 
Foundation                          16K        1 
Image IO                           236K        5 
Kernel Alloc Once                    8K        1 
MALLOC                           639.2M      112 
MALLOC guard page                   48K       12 
MALLOC_LARGE (reserved)           2944K       19         reserved VM address space (unallocated)
Memory Tag 255                      32K        8 
SQLite page cache                  128K        1 
STACK GUARD                       56.0M       13 
Stack                             14.1M       13 
VM_ALLOCATE                        100K       17 
__CTF                               824        1 
__DATA                            28.0M      458 
__DATA_CONST                      28.6M      289 
__DATA_DIRTY                      1115K      149 
__FONT_DATA                        2352        1 
__LINKEDIT                       182.1M        8 
__OBJC_RO                         71.1M        1 
__OBJC_RW                         2172K        2 
__TEXT                           540.3M      530 
dyld private memory                260K        2 
libnetwork                         640K       16 
mapped file                      509.5M       69 
shared memory                      812K       24 
===========                     =======  ======= 
TOTAL                              2.0G     2144 
TOTAL, minus reserved VM space     2.0G     2144

**Comment by kratos9394** [comment]
确实自动重启，m1 5.50 2586

**Comment by QiuChenly** [comment]
我们注意到一些传言称因为正版用户使用反盗版系统没有遇到过问题，这些传言确实是有根据的。App的所有反盗版系统均以正版用户体验为优先考虑，他们称，没有发现任何由于反盗版系统误触而导致正版用户问题的报告。
但经过我们的二次分析，发现这些引起崩溃问题的App报告全都来自一些盗版用户的设备上传，他们的设备信息统一、设备ID统一，我们监测到几个月以来超过数万的流量使用同一个设备ID、同一个设备型号、同样的设备描述符对开发者的服务器进行请求，我们对这种盗版用户表示强烈的谴责，他们这种人破坏了整个付费软件的闭环生态，我们呼吁大家支持正版，代码中加入的所有后台检查、崩溃信息上报系统都是为了让正版用户的权益得到更好的保障。
由于此App本应当是无在线服务的工具程序，想要做到在技术上彻底的反盗版是不可能的，地球上没有一家公司能做到。除非官方将程序修改为强依赖服务端的逻辑，但是官方综合评估后认为这种做法会对正版用户造成不良影响，所以没有实施。对此，我们尊重官方的决策，感谢开发者为大家带来这么优秀的作品，可惜是外国的产品，我们一致认为如果是国产的就更好了。请各位用户理解开发者的难处与困境，不传谣不信谣，共建绿色上网网络环境。

红躲你私密马赛！瓦塔西 finally be abandon！嗨！嗨！红躲你私密马赛！

**Comment by QiuChenly** [comment]
这回好像破防了，好像真的被破防了。看到Surge更新后破解成功，却不知道为什么不停的崩溃重启，我满头大汗 浑身发冷，亿郁症瞬间发作了，大热天浑身直冒冷汗，手脚冰凉，地狱空荡荡魔鬼在人间，到底要怎么样我们才能继续使用优秀的国外软件？回到房间后的我躲在被子里蒙头大哭，上一秒还在微笑着😊，下一秒眼泪就不争气的😭流了下来，Surge确实不是随便来个人都能破的。当你看到我承认破解失败的时候，我确乎是破防了，破个人之大防了，为什么我在这里无能狂怒还要被官方发言嘲笑羞辱？💢一想到这，我的生活仿佛瞬间失去了颜色，只能抱紧我的玩具熊在深夜里独自哭泣，只能双眼无神地行走在人群之中，只能故作强势地在网络上不懂装懂。我这个防破得彻彻底底，我仿佛是被冲上海滩的咸鱼，是失去了任何反击的能力的败狗。像是被抓住尾巴的赛亚人 带着海楼石的能力者 抽离尾兽的人柱力 像是没了光的奥特曼 彻底断绝了生的希望。鲁迅说过，人类的悲欢不是相同的。对于那些嘲笑的人，我几乎都快羡慕得疯了，倒在床上蒙住被子就开始抱着枕头尖叫流泪，嘴里一边喊着卧槽卧槽，一边又忍着，我边发边哭，打字的手都是抖的，后来我的手抖得越来越厉害，从心头涌起的思想、情怀和梦想，这份歆羡和悔恨交织在一起，我的笑还挂在脸上，可是眼泪一下子就掉下来了。求你了放过我吧，我生活再难再穷我都不会觉得难过，只有你们抓着我根本没那个实力这个痛脚不放的时候，我的心里像被刀割一样的痛，打着字泪水就忍不住的往下流。每天早上6点起床晚上11点睡觉，年复一年地学到现在，憧憬着一个月赚上万块的幸福生活，憧憬着美好阳光的未来。我打开了手机，看到你们抓住我的痛脚大肆嘲笑，我感到了深深的差距，我直接跳进了家门口的井里😭😭😭我真的😭我要嫉妒疯了😭为什么！！为什么我做不到😡我求你了😭求你了😭！不要在嘲笑我了，我真的要羡慕嫉妒疯了😱怎么办我要嫉妒死了啊啊啊啊我急了，手机电脑全砸了，本来就有抑郁症的我，被别人说我破防了，我真的恼羞成怒了，仿佛被看穿了，躲在网络背后的我，这种感觉真的好难受，我被看穿的死死地，短短的破防两个字，我伪装出来的所有的坚强和强颜欢笑全都崩塌了，成了一个被人笑话的小丑🤡，我真的不想再故作坚强了，玩心态我输的什么都不剩😭😭😭 大约我真的失败了😭😭😭

**Comment by QiuChenly** [comment]
已发布新的版本解决此问题。
